- name: Remove new VM using cloud-init with a username and password
  community.general.proxmox_kvm:
    node: "{{ proxmox_node }}"
    api_user: "{{ proxmox_username}}"
    api_password: "{{ proxmox_password }}"
    api_host: "{{ proxmox_hostname }}"
    name: "{{ vmname }}.{{ zone }}"
    state: stopped
  when: remove_vm


- name: Remove new VM using cloud-init with a username and password
  community.general.proxmox_kvm:
    node: "{{ proxmox_node }}"
    api_user: "{{ proxmox_username}}"
    api_password: "{{ proxmox_password }}"
    api_host: "{{ proxmox_hostname }}"
    name: "{{ vmname }}.{{ zone }}"
    state: absent
  when: remove_vm